#!/bin/bash
set -e
repo="sickp/alpine-redis"
latest=$(ls -r versions | head -1)
tags="3.0 3 latest"
version=${1:-$latest}

docker build -t ${repo}:${version} --pull versions/${version}
echo "=> Built ${repo}:${version}"
if [[ $latest == $version ]]; then
  for tag in ${tags}; do
    docker tag -f ${repo}:${version} ${repo}:${tag}
    echo "=> Tagged ${repo}:${tag}"
  done
fi
