#!/bin/bash
set -e

repo=sickp/alpine-redis
latest=3.0.6
tags="3.0 3 latest"
version=${1:-$latest}

docker build -t ${repo}:${version} --pull versions/${version}
echo "=> Built ${repo}:${version}"
docker build -t ${repo}:${version}-k8s --pull versions/${version}-k8s
echo "=> Built ${repo}:${version}-k8s"

if [[ $latest == $version ]]; then
  for tag in ${tags}; do
    docker tag -f ${repo}:${version} ${repo}:${tag}
    echo "=> Tagged ${repo}:${tag}"
  done
fi
